### ISSUE TITLE
Add MINIMAL pragmas

### ISSUE THREAD

**Issue by feuerbach** [ekmett/mtl#12]
From a quick look, the following classes would benefit from [MINIMAL pragmas](http://www.haskell.org/ghc/docs/7.8.2/html/users_guide/pragmas.html#minimal-pragma) since they have recursive method definitions:

* MonadState
* MonadWriter

Maybe some others that I missed.

**Comment by ekmett** [comment]
Shipped in 2.2.1 on Jun 2, 2014, but this issue was never closed. Resolving.
