### ISSUE TITLE
Documentation on http://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Identity.html contains a small mistake

### ISSUE THREAD

**Issue by natschil** [ekmett/mtl#20]
The documentation cited in the title contains the line "Identity x >>= f == Identity (f x)". However, if I am not mistaken, this is wrong: it should read "Identity x >>= f == f x".

**Comment by ekmett** [comment]
Indeed. Fixed in 452b6b5 by @dmjio on Jun 15, 2014.
