### ISSUE TITLE
Uneasy with example using `fromJust`

### ISSUE THREAD

**Issue by FranklinChen** [ekmett/mtl#23]
`Reader.hs` documentation has an example that makes me very uneasy because it uses `fromJust`. I think code snippets make a big impression on newcomers and the example code to illustrate `Reader` is not anything anyone would really write because it doesn't account for errors.

```haskell
lookupVar :: String -> Bindings -> Int
lookupVar name bindings = fromJust (Map.lookup name bindings)
```

**Comment by ekmett** [comment]
I'd happily take a pull request to change the example to something more neutral.

**Comment by tmcgilchrist** [comment]
Regarding an improvement to this example, would you consider it enough that there is a non-partial function in place of `fromJust` e.g.

```haskell
-- The Reader monad, which implements this complicated check.
calc_isCountCorrect :: Reader Bindings Bool
calc_isCountCorrect = do
  count <- asks (lookupVar "count")
  bindings <- ask
  return . boolM $ ((== (Map.size bindings)) <$> count )

-- Not really a good idea?
boolM :: Maybe Bool -> Bool
boolM Nothing = False
boolM (Just b) = b
```

**Comment by ekmett** [comment]
We could just call `maybe` appropriately instead.

**Comment by ekmett** [comment]
Merged
